### ISSUE TITLE
Could not create an native instance of the type 'Xamarin.Nuke.ImagePipeline': the native class hasn't been loaded.

### ISSUE THREAD

**Issue by roubachof** [roubachof/NukeProxy#11]
Is there some initialization to do with the net6 version?
I get this exception when trying to create a new pipeline:

```csharp
public static Task<UIImage?> LoadImageAsync(NSUrl url, Action<string>? onFail)
    {
        var tcs = new TaskCompletionSource<UIImage?>();

        var pipeline = new ImagePipeline();

        // ImagePipeline.Shared.LoadImageWithUrl(

        pipeline.LoadImageWithUrl(
            url,
            (image, errorMessage) =>
                {
                    if (image == null)
                    {
                        onFail?.Invoke(errorMessage);
                    }

                    tcs.SetResult(image);
                });

        tcs.SetResult(null);

        return tcs.Task;
    }
```

```
System.Exception: Could not create an native instance of the type 'Xamarin.Nuke.ImagePipeline': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
   at Foundation.NSObject.InitializeObject(Boolean alloced)
   at Foundation.NSObject..ctor(NSObjectFlag x)
   at Xamarin.Nuke.ImagePipeline..ctor()
   at Maui.Nuke.NukeController.LoadImageAsync(NSUrl url, Action`1 onFail) in D:\Dev\Sharpnado\src\Maui.Nuke\Maui.Nuke\NukeController.cs:line 14
   at Maui.Nuke.NukeFileImageSourceService.GetImageAsync(IImageSource imageSource, Single scale, CancellationToken cancellationToken) in D:\Dev\Sharpnado\src\Maui.Nuke\Maui.Nuke\NukeFileImageSourceService.cs:line 90
[0:] Microsoft.Maui.UriImageSourceService: Error: Fail to load image: https://i.pinimg.com/originals/94/9b/f6/949bf6697db43904f1da1deab6938e7c.gif
```

repo => https://github.com/roubachof/Maui.Nuke

**Comment by Cheesebaron** [comment]
@roubachof does this happen on device or simulator?

If device, is it a iPhone or MacCatalyst?
If simulator, do you know which RuntimeIdentifier is being selected?

**Comment by roubachof** [comment]
hey ! It was with my iphone XR I think.
I tried to have confirmation of this but stumbled upon this issue: https://github.com/xamarin/xamarin-macios/issues/16001#issuecomment-1252984909
I guess I will try again with my mac this time

**Comment by roubachof** [comment]
Yup, it's working on my mac mini, so I guess it's a vs windows issue !
