### ISSUE TITLE
Issue when restoring the nuget package

### ISSUE THREAD

**Issue by roubachof** [roubachof/NukeProxy#20]
Recently, it seems that a new error is appearing when restoring the ImageCaching.Nuke package.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Jean-Marie\.nuget\packages\imagecaching.nuke\3.0.0\lib\net6.0-maccatalyst16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
```

see: https://github.com/roubachof/Maui.Nuke/issues/5#issuecomment-1875748378

But also if you try to open the https://github.com/roubachof/Maui.Nuke/ solution, you will end up with the same issue:

```
Restoring packages for D:\Dev\Sharpnado\src\Maui.Nuke\Maui.Nuke\Maui.Nuke.csproj...
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='ImageCaching.Nuke'&semVerLevel=2.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='ImageCaching.Nuke'&semVerLevel=2.0.0 461ms
  GET https://www.nuget.org/api/v2/package/ImageCaching.Nuke/3.0.0
  OK https://www.nuget.org/api/v2/package/ImageCaching.Nuke/3.0.0 172ms
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Jean-Marie\.nuget\packages\imagecaching.nuke\3.0.0\lib\net6.0-maccatalyst16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at NuGet.Packaging.StreamExtensions.Testable.MmapCopy(Stream inputStream, String fileFullPath, Int64 size)
   at NuGet.Packaging.StreamExtensions.Testable.CopyToFile(Stream inputStream, String fileFullPath)
   at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
   at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<InstallPackageAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.ProjectRestoreCommand.<InstallPackagesAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<TryRestoreAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.RestoreRunner.<RunWithoutCommit>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<PreviewRestoreProjectsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectsActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectActionsAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForBuildIntegratedAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass61_1.<<PreviewUpdatePackagesAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass24_0.<<GetUpdateActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__33`1.MoveNext()
Time Elapsed: 00:00:05.5090691
========== Finished ==========
```

It seems that the simulator target is missing some files.
For example here is the arm64 target swiftmodule folder:

![image](https://github.com/roubachof/NukeProxy/assets/596903/292f1e43-7af1-444c-9b16-85e84587dcd9)

And here is the simultor target folder:

![image](https://github.com/roubachof/NukeProxy/assets/596903/8d4f56a0-ed30-4d08-8413-a89321e7eb33)

For some reason it was working in .net6 but it's failing on .net7

**Comment by Cheesebaron** [comment]
Seems to work fine on macOS:

![image](https://github.com/roubachof/NukeProxy/assets/249719/2c98b32f-6bb9-4e17-a6bf-72aaf1a76e38)

I only bumped TFM to `net7.0-ios;net7.0-maccatalyst`. Cannot get it to work when it is the old `net6.0-*` TFMs.

Perhaps it is a Windows issue?

**Comment by Cheesebaron** [comment]
@roubachof is this something we need to look further into?

**Comment by roubachof** [comment]
I'm not really sure if it's really a windows issue or a packaging of the simulator arch, since it indeed misses some files if you compared it to other arch.

**Comment by tolgraven** [comment]
I think it's universal, happens on our macos build host anyways

**Comment by Cheesebaron** [comment]
@roubachof do you still have this issue?

I think it might be due to the long paths. Since I noticed when building the NuGet package CI throws warnings like this:

```
Warning: /Users/runner/.dotnet/sdk/9.0.203/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5123: The file 'lib/net8.0-ios18.0/ImageCaching.Nuke.resources/Nuke.xcframework/ios-arm64_x86_64-simulator/Nuke.framework/Modules/Nuke.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/Users/runner/work/NukeProxy/NukeProxy/src/ImageCaching.Nuke/ImageCaching.Nuke.csproj]
```

**Comment by SirJohnK** [comment]
@roubachof , I am getting this issue when trying to install the Sharpnado.Maui.Nuke 12.8.3 NuGet package today and do not know how to solve it!?

**Comment by Cheesebaron** [comment]
@SirJohnK can you help providing a bit more detail on:

- What kind of project are you installing the package in? I am mainly interested in which `TargetFrameworks` this project has
- Which OS are you using?

Any other details you can provde would be helpful in figuring out what is going on.

Also please provide output of the following commands:

```
dotnet --version
```

and 

```
dotnet workload list
```

**Comment by JohanKSvensson** [comment]
Hi @Cheesebaron,

- I tried different MAUI projects, but the main is a MAUI App project targeting `net9.0-android;net9.0-ios`.
- Running Visual Studio 2026 on Windows.

Error:

> Could not find a part of the path 'C:\Users\aae367\.nuget\packages\imagecaching.nuke\4.1.1\lib\net8.0-ios18.0\ImageCaching.Nuke.resources\NukeExtensions.xcframework\ios-arm64_x86_64-simulator\NukeExtensions.framework\Modules\NukeExtensions.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.

dotnet --version

> 10.0.102

dotnet workload list

> Workload version: 10.0.100-manifests.6d969a7e
> 
> Installed Workload Id      Manifest Version         Installation Source
> ---------------------------------------------------------------------------------------
> android                    36.1.2/10.0.100          VS 17.14.36908.2, VS 18.2.11408.102
> ios                        26.1.10502/10.0.100      VS 17.14.36908.2, VS 18.2.11408.102
> maccatalyst                26.1.10502/10.0.100      VS 17.14.36908.2, VS 18.2.11408.102
> maui-windows               10.0.1/10.0.100          VS 17.14.36908.2, VS 18.2.11408.102

Frustration because I really would like to replace `FFImageLoading` that we currently are using.

/Regards Johan

**Comment by Cheesebaron** [comment]
I would try the following.

If you are using Central Package Management with transitively pinned packages simply adding the following like to your `Directory.Packages.props`:

```xml
<PackageVersion Include="ImageCaching.Nuke" Version="5.0.0" />
```

If you don't have pinning enabled. Also add the corresponding line to the project where you are consuming the pacakge.

```xml
<PackageReference Include="ImageCaching.Nuke />
```

If you are not using CPM then adding to your project:

```xml
<PackageReferemce Include="ImageCaching.Nuke" Version="5.0.0" />
```

For the 2 last points you will need to conditionally add it only for iOS as the package is not compatible with other targets. Something like:


```xml
<ItemGroup Condition="$(TargetFramework.Contains('ios'))">
  <PackageReferemce Include="ImageCaching.Nuke" Version="5.0.0" />
</ItemGroup>
```

**Comment by SirJohnK** [comment]
Hi again,

It seems like the issue is with the `4.1.1` version and since `Sharpnado.Maui.Nuke` attempts to install that version.
Explicit using the `5.0.0` seems to solve the issue.

@roubachof , maybe a good idea to update `Sharpnado.Maui.Nuke` to require the `5.0.0` version of `ImageCaching.Nuke`.

Thanks! 👍

**Comment by roubachof** [comment]
Thanks Johann!

Could you open an issue in Maui nuke repo so I can track it please?
